are/apps/admin/urls.py
from django.urls import path
from . import views
# from .views import logout
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
# from django.urls import path, reverse_lazy

# app_name = "admin"

urlpatterns = [
	path('login/', views.AdminLogin.as_view(), name='admin_login'),
    path('logout/', views.AdminLogout.as_view(), name='logout'),
	path('dashboard/',views.DashboardView.as_view(),name='admin_dashboard'),
	path('speakers/', views.AdminViewSpeaker.as_view(), name='speaker_admin'),
	path('awards/', views.AdminViewawards.as_view(), name='awards_admin'),
	path('agenda/', views.AdminViewagenda.as_view(), name='agendas_admin'),
	path('partner/', views.AdminViewPartner.as_view(), name='partner_admin'),
	path('sponsor/', views.AdminViewSponsor.as_view(), name='sponsor_admin'),

	path('adminaddspeaker/', views.AdminSpeakerCreateView.as_view(), name='admin_add_speaker'),
	path('deletespeaker/<int:pk>', views.SpeakerDeleteView.as_view(), name='speaker_delete'),
	path('updatespeaker/<int:pk>', views.SpeakerUpdateView.as_view(), name='speaker_update'),
    path('editspeakerpopup/', views.edit_speaker_popup, name='admin_speaker_edit'),
    path('editagendapopup/', views.edit_agenda_popup, name='admin_agenda_edit'),
]

are/apps/agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'
urlpatterns = [
	path('',views.AgendaView.as_view(),name='agenda_list'),
	path('conferenceadd/',views.ConferenceCreateView.as_view(),name='conference_add'),
	path('agenda_add/',views.MyFormView.as_view(),name='agenda_add'),
	# path('agenda_add/',views.agenda_new,name='agenda_add'),
	path('edit-session-popup/',views.edit_session_popup,name='edit_session_popup'),

	]


	# path('',views.ConferenceView.as_view(),name='conference_list'),
	# path('conference/',views.ConferenceListView.as_view(template_name='agenda.html'),name='conference_list'),
	# path('conference/',views.conferencelist,name='conference_list'),
	# path('agenda_add/',views.AgendaCreateView.as_view(),name='agenda_add'),
	# path('conference/',views.ConferenceListView.as_view(template_name='agenda.html'),name='conference_list'),
	# path('conference/',views.conferencelist,name='conference_list'),
	# path('agenda_add/',views.AgendaCreateView.as_view(),name='agenda_add'),
	# path('list/',views.AgendaView.as_view(),name='agenda_list'),
	# path('addagenda/',views.AgendaCreateView.as_view(),name='agenda_add'),
	# path('conferencedelete/',views.ConferenceDeleteView.as_view(),name='conference_delete'),
	# path('conferenceupdate/',views.ConferenceUpdateView.as_view(),name='conference_update'),
	# path('deleteagenda/',views.AgendaDeleteView.as_view(),name='delete_agenda'),
	# path('updateagenda/',views.AgendaUpdateView.as_view(),name='update_agenda'),
	

are/apps/awards/urls.py
from django.urls import path
from .models import AmgAward
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'awards'

urlpatterns = [
	# path('admin/dashboard/',views.DashboardView.as_view(),name='dashboard'),
	path('challange_award/',views.ChallengeAwardView.as_view(),name='challenge_award'),
	path('amg_awards/',views.AmgAwardView.as_view(),name='amg_award'),
	path('award/',views.AwardView.as_view(),name='award'),
	path('application/',views.AmgApplicationFormView.as_view(),name='application'),
	path('',views.HomePageView.as_view(),name='home'),
	path('ourpartner/',views.PartnerView.as_view(),name='partner'),
	path('ourpartner/register/',views.PartnerRegisterView.as_view(),name='partner_register'),
	path('oursponsor/register/',views.SponsorRegisterView.as_view(),name='sponsor_register'),
	path('context/',views.ContextView.as_view(),name='context'),
	path('thanks/',views.ThanksEnergyView.as_view(),name='thanks'),
	path('amg_applicants/',views.AdminViewAmgApplicant.as_view(), name='amg_applicants'),
	path('amg_applicants/<int:pk>',views.AdminDetailViewAmgApplicant.as_view(), name='amg_applicant_detail'),
	path('application_form/<int:pk>',views.ClimateApplicationForm.as_view(),name='climate_application_form'),
	path('privacy_policy/',views.Privacypolicy.as_view(),name='privacy_policy'),
	path('climate_table/',views.ClimateTable.as_view(),name='climate_table'),
	path('terms_services/',views.Termsservices.as_view(),name='terms_services'),
	path('climate_applicants/',views.AdminViewClimateApplicant.as_view(),name='climate_applicants'),
	path('climate_applicants/<int:pk>',views.AdminDetailViewClimateApplicant.as_view(), name='climate_applicants_detail'),
	path('sendmail/',views.sendMail,name='email'),
	path('shell-gamechanger/',views.Shellgamechanger.as_view(),name='shell-gamechanger'),
	path('session_detail/',views.SessionDetail.as_view(),name='session_detail'),
	path('are_conference2022/',views.AreConference2022.as_view(),name='are_conference2022'),
	path('are_conference2023/',views.AreConference2023.as_view(),name='are_conference2023'),
    path('sponsors/',views.SponsorView.as_view(),name='sponsors'),
	path('Sawraj_award2022/',views.Sawrajaward.as_view(),name='Sawraj_award2022'),
	path('media-img/',views.Mediaimg.as_view(),name='media-img'),
	path('media/',views.MediaFront.as_view(),name='media'),
	path('register/',views.Register.as_view(),name='register'),
    path('media-detail/',views.Mediadetail.as_view(),name='media-detail'),   
	path('swaraj_award2023/',views.Swarajaward2023.as_view(),name='swaraj_award2023'), 

	# redirection static media pages
   	path('inauguration/',views.Inauguration.as_view(),name='inauguration'), 
   	path('session1_images/',views.Session1_Images.as_view(),name='session1_images'), 
   	path('session2_images/',views.Session2_Images.as_view(),name='session2_images'), 
   	path('session3_images/',views.Session3_Images.as_view(),name='session3_images'), 
   	path('session4_images/',views.Session4_Images.as_view(),name='session4_images'), 
   	path('session5_images/',views.Session5_Images.as_view(),name='session5_images'), 
   	path('session6_images/',views.Session6_Images.as_view(),name='session6_images'), 
   	path('session7_images/',views.Session7_Images.as_view(),name='session7_images'), 
   	path('session8_images/',views.Session8_Images.as_view(),name='session8_images'), 
   	path('ebooklaunch/',views.Ebooklaunch.as_view(),name='ebooklaunch'), 
   	path('esaphotos/',views.ESAphotos.as_view(),name='esaphotos'), 
   	path('expostalls/',views.Expostalls.as_view(),name='expostalls'), 
   	path('randomclick/',views.Randomclick.as_view(),name='randomclick'), 
   	path('shellganechanger/',views.Shellgamechanger.as_view(),name='shellganechanger'),

    # path('inauguration/',views.Mediavideo.as_view(),name='inauguration'), 
	
	
	
	


	# path('agenda_detail/',views.Adminagenda.as_view(),name='agenda_detail'),
	# path('speaker/',views.Adminspeker.as_view(),name='speaker'),
	# path('awards/',views.Adminaward.as_view(),name='awards'),
	# path('dashboard/',views.dashboard.as_view(),name='dashboard'),
	path('text-file/<int:pk>', views.text_file, name='text-file'),
	path('text-file1/<int:pk>', views.text_file1, name='text-file1'),

]

are/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = [
    path('super/admin/', admin.site.urls),
    path('',include('awards.urls')),
    path('speakers/',include('speakers.urls')),
    path('admin/',include('admin.urls')),
    path('agenda/',include('agenda.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

are/apps/admin/models.py
from django.db import models

# Create your models here.

are/apps/admin/forms.py
from django import forms
from speakers.model import Speaker
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
                'username',
                'password',
        ]

class UpdateSpeakerForm(forms.ModelForm):
    class Meta:
        model = Speaker
        fields = [
                'name','profile_image',
                'designation','detail'
        ]

are/apps/agenda/forms.py
from django import forms
from .models import Agenda,Conference


class ConferenceForm(forms.ModelForm):
	class Meta:
		model = Conference
		fields = ['title', 'startdate', 'enddate']
		

class AgendaForm(forms.ModelForm):
	class Meta:
		model = Agenda
		fields = ['conference', 'session', 'date','starttime', 'endtime', 'duration', 'event', 'speaker']

are/apps/speakers/forms.py
from django import forms
from .models import Speaker

class SpeakerForm(forms.ModelForm):
	class Meta:
		model = Speaker
		fields = ['name','profile_image','designation','detail']

are/apps/admin/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView 
from django.views.generic.edit import DeleteView, UpdateView
from django.contrib.auth.views import LoginView,LogoutView
from speakers.models import Speaker
from awards.models import Award,AmgAward,ClimateAward,PartnerRegister, SponsorRegister
from agenda.models import Conference,Agenda
from speakers.forms import SpeakerForm
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib import auth, messages
from django.contrib.auth import login, logout
from django.http import Http404
import json
import pandas as pd
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here

class AdminLogin(LoginView):
	template_name = 'admin/admin_login.html'

	def post(self, request, *args, **kwargs):
		
		form = self.get_form()
		if form.is_valid():
			
			username = request.POST['username']
			password = request.POST['password']
			user = auth.authenticate(username = username, password = password)
			if user is not None and user.is_staff == True:
				login(request, user)
				return redirect('admin_dashboard')
		else:
			return self.form_invalid(form)


class AdminLogout(LogoutView):
	success_url = '/'


class DashboardView(LoginRequiredMixin,TemplateView):
	modal = Speaker
	template_name = "dashboard.html"
	login_url='/admin/login/'

	def get_context_data(self, **kwargs):
		total_speaker = Speaker.objects.all().count()
		total_awards = AmgAward.objects.all().count()
		total_climate = ClimateAward.objects.all().count()

		data = {
			'total_speaker':total_speaker,
			'total_awards':total_awards,
			'total_climate':total_climate,
		}
		return {'data':data} 


class AdminViewSpeaker(LoginRequiredMixin,ListView):
	model = Speaker
	template_name = "admin_speaker.html"
	login_url='/admin/login/'
	ordering = ['id']


class AdminViewPartner(LoginRequiredMixin,ListView):
	model = PartnerRegister
	template_name = "admin_partner.html"
	login_url='/admin/login/'
	ordering = ['id']

class AdminViewSponsor(LoginRequiredMixin,ListView):
	model = SponsorRegister
	template_name = "admin_sponsor.html"
	login_url='/admin/login/'
	ordering = ['id']

class AdminSpeakerCreateView(CreateView):
	model = Speaker
	form_class = SpeakerForm
	# template_name = 'admin_speaker.html'

	def post(self, request, *args, **kwargs):
		name = request.POST.get("name")
		designation = request.POST.get("designation")
		detail = request.POST.get("detail")
		profile_image = request.FILES['profile_image']
		speaker_register = Speaker(name=name,designation=designation,detail=detail,profile_image=profile_image)
		speaker_register.save()

		return redirect("/admin/speakers/")

class AdminViewawards(LoginRequiredMixin,ListView):
	model = Speaker
	template_name = "admin_awards.html"
	login_url='/admin/login/'

	def get_context_data(self, **kwargs):
		total_speaker = Speaker.objects.all().count()
		total_awards = AmgAward.objects.all().count()
		total_climate = ClimateAward.objects.all().count()

		data = {
			'total_speaker':total_speaker,
			'total_awards':total_awards,
			'total_climate':total_climate,
		}

		return {'data':data} 


class AdminViewagenda(LoginRequiredMixin,ListView):
	template_name = 'admin_agendas.html'	
	queryset = Conference.objects.all().order_by('startdate')
	login_url='/admin/login/'
	
	def get_context_data(self, **kwargs):
		context = {}
		if self.queryset:
			# context = super(AgendaView, self).get_context_data(**kwargs)
			if len(self.queryset)>0:
				context['conf'] = self.queryset[0]
			else:
				context['conf'] = None
			datelist = pd.date_range(start=context['conf'].startdate,end=context['conf'].enddate)
			indexlist = [i+1 for i in range(len(datelist))]
			# context['agenda'] = Agenda.objects.all()	
			agenda = Agenda.objects.all().filter(conference_id = context['conf'].id)

			data = {}
			for index, item in zip(indexlist, datelist):
				if agenda:
					data[str(index)] = {
						'date':item.date(),
						'data':agenda.filter(date=item.date()).order_by('starttime')
					}
				else:
					data[str(index)] = {
						'date':item.date(),
						'data':[]
					}

			context['agenda'] = data
			context['speakers'] = Speaker.objects.all()	
			return context
		else:
			context = {
				'conf':None,
				'agenda':{},
				'speakers': Speaker.objects.all()
			}
			return context


class SpeakerDeleteView(DeleteView):
    model = Speaker
    success_url = reverse_lazy("speaker_admin")
    template_name = 'delete.html'



class SpeakerUpdateView(UpdateView):
	model = Speaker
	form_class = SpeakerForm
	template_name = 'admin_speaker.html'
	fields = ['name','designation','detail','profile_image']


	def get_success_url(self, **kwargs):
		return self.object.get_absolute_url()

def edit_speaker_popup(request):
	if request.method =='GET':

		speaker_id = request.GET.get('speaker_id')
		speaker=Speaker.objects.get(id=speaker_id)

		context = {
			'speaker_id':speaker.id,
			'speaker_name':speaker.name,
			'speaker_desig':speaker.designation,
			'speaker_detail':speaker.detail,
			'speaker_profile':speaker.profile_image.url,
		}

		return JsonResponse(context)

	if request.method =='POST':

		speaker_id = request.POST.get('speaker_id')
		speaker_name = request.POST.get('name')
		speaker_desig = request.POST.get('designation')
		speaker_detail = request.POST.get('detail')
		speaker_profile = request.FILES['profile_image']

		speaker = Speaker.objects.get(id=int(speaker_id))
		speaker.name=speaker_name
		speaker.designation=speaker_desig
		speaker.detail=speaker_detail
		speaker.profile_image=speaker_profile

		speaker.save()

		return redirect("/admin/speakers/")
		

# def edit_seats(request):
# 	if request.method =='GET':
# 		seat_id = request.GET.get('seat_id')
# 		seat_obj = Seats.objects.get(id=seat_id)
# 		context = {}
# 		context = {
# 		    'seat_obj_id': seat_obj.id,
# 		    'seat_no': seat_obj.remaining_seats
# 		}
# 		return JsonResponse(context)
# 	if request.method =='POST':
# 		seat_id = request.POST.get('seat_id')
# 		seat_obj = Seats.objects.get(id=seat_id)
# 		remaining_seat = request.POST.get('remaining_seat')


def edit_agenda_popup(request):
	if request.method =='GET':
		agenda_id = request.GET.get('agenda_id')
		agenda = Agenda.objects.get(id=agenda_id)
		speaker = Speaker.objects.all()
		data = speaker.values_list('pk','name')
		data1 = list(data)
		all_speakers = []
		for items in data1:
			res_dct = {
				'id':items[0],
				'name':items[1]
			}
			# res_dct = {item[i]: item[i + 1] for i in range(0, len(item), 2)}
			all_speakers.append(res_dct)

		context = {
			'agenda_id':agenda.id,
			'agenda_date':agenda.date,
			'agenda_session':agenda.session,
			'agenda_start':agenda.starttime,
			'agenda_end':agenda.endtime,
			'agenda_event':agenda.event,
			# 'agenda_speaker_id':agenda.speaker.id,
			# 'agenda_speaker_name':agenda.speaker.name,
			'speakers':all_speakers
		}
		if agenda.speaker:
			context['agenda_speaker_id'] = agenda.speaker.id
			context['agenda_speaker_name'] = agenda.speaker.name

		return JsonResponse(context)

	if request.method =='POST':
		agenda_id = request.POST.get('agenda_id')
		agenda_date = request.POST.get('date')
		agenda_session = request.POST.get('edit-session')
		if agenda_session:
			pass
		else :
			agenda_session = None
		agenda_start = request.POST.get('starttime')
		agenda_end = request.POST.get('endtime')
		agenda_event = request.POST.get('edit-event')
		speaker_id = request.POST.get('speaker')
		if speaker_id:
			speaker = Speaker.objects.get(id=int(speaker_id))
		else:
			speaker = None
		agenda = Agenda.objects.get(id=int(agenda_id))
		agenda.session = agenda_session
		agenda.date = agenda_date
		agenda.starttime = agenda_start
		agenda.endtime = agenda_end
		agenda.event = agenda_event
		agenda.speaker = speaker

		agenda.save()

		return redirect("/admin/agenda/") 

are/apps/speakers/views.py
from django.shortcuts import render
from .models import Speaker 
from speakers.forms import SpeakerForm
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

	
# Create your views here.

class SpeakerView(ListView):
	model = Speaker
	template_name = "speaker.html"
	ordering = ['id']


class SpeakerCreateView(CreateView):
	model = Speaker
	form_class = SpeakerForm

	def get_success_url(self, **kwargs):
		return self.object.get_absolute_url()

are/templates/add_agenda_popup.html
<!doctype html>
<html lang="en">

<head>
</head>

<body>
    <div id="add_session" class="modal fade">
        <div class="modal-dialog modal-login">
            <div class="modal-content">
                <form action="{% url 'agenda:agenda_add' %}" method="post" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="modal-header">
                        <h4>Add Agenda</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" name="conference" hidden class="form-control" id="conf_id_input" placeholder="time" value="{{ conf.pk }}">
                            <input type="date" name="date" class="form-control" id="datepicker1" placeholder="yyyy-mm-dd">
                            <label for="">session</label>
                            <input type="choice" name="session" class="form-control" id="" placeholder="session">
                            <label for="">Start Time</label>
                            <input type="time" name="starttime" class="form-control" id="" placeholder="time" required="true">
                            <label for="">End Time</label>
                            <input type="time" name="endtime" class="form-control" id="" placeholder="time" required="true">
                            <label for="">Event</label>
                            <textarea name="event" class="form-control" id="" placeholder="Detail" required=""> </textarea>
                            <label for="">Speaker</label>
                            <select name="speaker" class="form-control" id="" required>
                                <option value="">Select Speaker</option>
                                {% for speaker in speakers %}
                                    <option value="{{ speaker.id }}">{{ speaker.name }}</option>
                                {% endfor %}
                            </select>
                            <input type="submit" class="btn btn-primary" value="add">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-between">
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
    <!-- <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script> -->
    <script type="text/javascript">
    $(document).ready(function() {
        var min_date = `{{conf.startdate|date:"Y-m-d"}}`;
        var max_date = `{{conf.enddate|date:"Y-m-d"}}`;
        min = min_date;
        max = max_date;

        $('#datepicker1').attr('min', min_date);
        $('#datepicker1').attr('max', max_date);
        // $('#datepicker1').datepicker({
        //     minDate:min_date,
        //     maxDate:max_date,
        // });
    });
    </script>
</body>

</html>

are/templates/admin_awards.html
{% extends "layout/admin_base.html" %}
{% load static %}
{% block content %}
<section class="dashboard_area">
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-md-2">
                <div id="sidebar" role="navigation">
                    <ul>
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin_dashboard' %}">dashboard</a></li>
                        {% comment %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'speaker_admin' %}">Speakers</a></li>
                        {% endcomment %}
                        <li class="nav-item active"><a class="nav-link" href="{% url 'awards_admin' %}">Awards</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'partner_admin' %}">Partners</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'sponsor_admin' %}">Sponsors</a></li>
                        {% comment %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'agendas_admin' %}">Agenda</a></li>
                        {% endcomment %}
                    </ul>
                </div>
            </div>
            <div class="col-md-10">
                <div class="dashboard_right">
                    <div class="award_head">
                        <h2>Awards</h2>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="award_card">
                                    <a href="{% url 'awards:amg_applicants' %}">
                                        <div class="card_custom">
                                            <h4>Energy Swaraj Awards</h4>
                                            <p>{{ data.total_awards }}</p>
                                            <p class="more"><a href="{% url 'awards:amg_applicants' %}">More</a></p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="award_card">
                                    <a href="{% url 'awards:climate_applicants' %}">
                                        <div class="card_custom">
                                            <h4>Climate Hackathon Challenge Award</h4>
                                            <p>{{ data.total_climate }}</p>
                                            <p class="more"><a href="{% url 'awards:climate_applicants' %}">More</a></p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock content %}
{% block extra_content %}
{% include 'popup/add_speaker_popup.html' %}
{% include 'popup/edit_speaker_popup.html' %}
{% endblock extra_content %}

are/templates/dashboard.html
{% extends "layout/admin_base.html" %}
{% load static %}
{% block content %}
<section class="dashboard_area">
    <div class="container-fluid">
        <div class="row no-gutters">
            <div class="col-md-2">
                <div id="sidebar" role="navigation">
                    <ul>
                        <li class="nav-item active"><a class="nav-link" href="{% url 'admin_dashboard' %}">dashboard</a></li>
                        {% comment %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'speaker_admin' %}">Speakers</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'agendas_admin' %}">Agenda</a></li>
                        {% endcomment %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'awards_admin' %}">Awards</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'partner_admin' %}">Partners</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'sponsor_admin' %}">Sponsors</a><li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10">
                <div class="dashboard_right">
                    <div class="card_pannel">
                        <div class="row">
                            {% comment %}
                            <div class="col-md-4">
                                <div class="card_custom">
                                    <h4>Total Speakers</h4>
                                    <p>{{data.total_speaker}}</p>
                                   
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="card_custom">
                                    <h4>Energy Award</h4>
                                    <p>{{data.total_awards}}</p>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="card_custom">
                                    <h4>Climate Hackathon</h4>
                                    <p>{{data.total_climate}}</p>
                                </div>
                            </div>
                            {% endcomment %}
                            {% comment %}
                            <div class="col-md-4">
                                <a href="{% url 'speaker_admin' %}">
                                    <div class="card_custom">
                                        <div class="row">
                                            <div class="col-md-8">
                                                <h4>Total Speakers</h4>
                                                <p>{{ data.total_speaker }}</p>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="right_di"><img src="{% static 'images/voice.png' %}" alt="" title="" /></div>
                                            </div>
                                        </div>
                                        <p class="more"><a href="{% url 'speaker_admin' %}">More</a></p>
                                    </div>
                                </a>
                            </div>
                            {% endcomment %}
                            <div class="col-md-4">
                                <a href="{% url 'awards:amg_applicants' %}">
                                    <div class="card_custom">
                                        <div class="row">
                                            <div class="col-md-8">
                                                <h4>Energy Award</h4>
                                                <p>{{ data.total_awards }}</p>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="right_di"><img src="{% static 'images/trophy.png' %}" alt="" title="" /></div>
                                            </div>
                                        </div>
                                        <p class="more"><a href="{% url 'awards:amg_applicants' %}">More</a></p>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-4">
                                <a href="{% url 'awards:climate_applicants' %}">
                                    <div class="card_custom">
                                        <div class="row">
                                            <div class="col-md-8">
                                                <h4>Climate Hackathon</h4>
                                                <p>{{ data.total_climate }}</p>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="right_di"><img src="{% static 'images/climate.png' %}" alt="" title="" /></div>
                                            </div>
                                        </div>
                                        <p class="more"><a href="{% url 'awards:climate_applicants' %}">More</a></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

are/templates/delete.html
<div id="deletepopup" class="modal fade">
    <div class="modal-dialog modal-login">
        <div class="modal-content">
            <div class="modal-header">
              <h4>Delete</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <form action="" name="form-delete-c" method="post">
                        {% csrf_token %}
                        <p>Are you sure you want to delete ?</p>
                        <button type="submit" style="background-color:red">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer justify-content-between">
        </div>
    </div>
</div>

are/templates/update.html
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
  <input class="btn btn-outline-info" type="submit" style="background-color:lightblue" value="Update" />
</form>

{% endblock content %}